// Generated by IcedCoffeeScript 1.3.3e
(function() {
  var assert, colors, express, fs, reachOut, startServer;

  fs = require('fs');

  colors = require('colors');

  assert = require('assert');

  express = require('express');

  startServer = function() {
    var expressServer;
    expressServer = express();
    expressServer.use(express.favicon('front/favicon.ico'));
    expressServer.use(express.bodyParser());
    expressServer.use('/js', express["static"]('front/js'));
    expressServer.use('/css', express["static"]('front/css'));
    expressServer.use('/img', express["static"]('front/img', {
      maxAge: 86400000
    }));
    expressServer.use('/json', express["static"]('front/json'));
    expressServer.get('/', function(request, response) {
      return response.sendfile('front/index.html');
    });
    expressServer.post('/reachOut', reachOut);
    expressServer.listen(9000);
    return console.log('Server started'.bold.magenta);
  };

  reachOut = function(request, response) {
    return response.end('cool');
  };

  startServer();

}).call(this);
