--- #Agles: 0.0.1
languages:
  python: 2.7
  ruby: 1.9.3
  nodejs: 0.8.9
setup:
  - packages:
    - system:
      - zlib1g
      - vim
      - gcc
      - g++
      - curl
      - libssl-dev
      - apache2-utils
      - libevent-dev
      - libpq-dev
      - lessc
    - pip:
      - amqp
      - pika: 0.9.5
      - kombu
      - librabbitmq
      - sqlalchemy
      - pyyaml
      - msgpack-python
      - nose
      - beautifulsoup4
      - dulwich
      - ipython
      - redis
      - greenlet
      - eventlet
      - gitpython
      - virtualenvwrapper
      - psycopg2
      - argparse
      - nose-testconfig
      - boto
    - npm:
      - iced-coffee-script
      - less
      - directory: ci/web/back
  - databases:
      postgres:
      - name: agles
        username: lt3
build:
  platform:
    path: ci/platform
    script: python setup.py install
  web:
    path: ci/web/back
    script: ./compile.sh
test:
  platform:
    path: ci/platform
    script: nosetests --tc=fakeverifier:True
  web:
    path: ci/web/back
    script: npm test
