---
setup:
  - packages:
    - system:
      - zlib1g
      - vim
      - gcc
      - g++
      - curl
      - libssl-dev
      - apache2-utils
      - libevent-dev
      - libpq-dev
      - lessc
    - pip:
      - amqp
      - pika
      - kombu
      - librabbitmq
      - sqlalchemy
      - pyyaml
      - msgpack-python
      - nose
      - beautifulsoup4
      - dulwich
      - ipython
      - redis
      - greenlet
      - eventlet
      - gitpython
      - virtualenvwrapper
      - psycopg2
      - argparse
      - nose-testconfig
      - boto
    - gem:
      - vagrant
    - npm:
      - iced-coffee-script
      - less
      - directory: ci/web/back
  - scripts:
    - script: ./install_virtualbox.sh
      directory: ci/scripts
    - script: vagrant gem install sahara
      user: true
  - databases:
      postgres:
      - name: agles
        username: lt3
languages:
  python:
    version: 2.7
    path: ci/platform
    testscript: nosetests --tc=fakeverifier:True
  ruby:
    version: 1.9.3
  node:
    version: v0.8.9
