---
setup:
  - packages:
    - system:
      - zlib1g
      - vim
      - gcc
      - g++
      - curl
      - libssl-dev
      - apache2-utils
      - libevent-dev
      - libpq-dev
    - pip:
      - pika
      - kombu
      - librabbitmq
      - sqlalchemy
      - pyyaml
      - msgpack-python
      - nose
      - beautifulsoup4
      - dulwich
      - ipython
      - redis
      - greenlet
      - gevent
      - gitpython
      - virtualenvwrapper
      - psycopg2
      - argparse
      - nose-testconfig
      - boto
    - gem:
      - vagrant
  - scripts:
    - script: ./install_node.sh
      directory: scripts
    - script: ./install_virtualbox.sh
      directory: scripts
  - packages:
    - npm:
      - iced-coffee-script
  - databases:
      postgres:
      - name: agles
        connection-info:
          host: localhost
          port: 5432
          username: postgres
  - scripts:
    # Currently failing, unable to find amqp.js?
    - script: npm install -d
      directory: web/back
build:
  python:
    version: 2.7
    buildscript:
    path: platform
    testscript: nosetests
