---
- packages:
  - system:
    - vim
    - vagrant
    - gcc
    - g++
    - curl
    - libssl-dev
    - apache2-utils
    - redis-server
    - libevent-dev
  - pip:
    - pika
    - sqlalchemy
    - pyyaml
    - msgpack-python
    - nose
    - beautifulsoup4
    - dulwich
    - ipython
    - redis
    - greenlet
    - gevent
- scripts:
  - script: /vagrant/scripts/install_node.sh
- packages:
  - npm:
    - iced-coffee-script
- databases:
    postgres:
    - name: agles
      connection-info:
        host: localhost
        port: 5432
        username: postgres
- scripts:
  # Currently failing, unable to find amqp.js?
  - script: npm -d install
    directory: /vagrant/web/back
  - script: redis-server
    background: true
