"""Remove build_commits_map table

Revision ID: 10c6543b5424
Revises: edfe8fda35e
Create Date: 2013-04-02 18:52:09.137946

"""

# revision identifiers, used by Alembic.
revision = '10c6543b5424'
down_revision = 'edfe8fda35e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('build', sa.Column('commit_id', sa.Integer(), nullable=True))

    build = sa.sql.table('build', sa.sql.column('id', sa.Integer()), sa.sql.column('commit_id', sa.Integer()))
    build_commits_map = sa.sql.table('build_commits_map', sa.sql.column('build_id', sa.Integer()), sa.sql.column('commit_id', sa.Integer()))

    build_to_commits = op.get_bind().execute(build_commits_map.select())
    for build_to_commit in build_to_commits:
        op.get_bind().execute(
            build.update().values(commit_id=build_to_commit[build_commits_map.c.commit_id]).where(build.c.id == build_to_commit[build_commits_map.c.build_id])
        )

    op.alter_column('build', 'commit_id', nullable=False)
    op.drop_table(u'build_commits_map')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table(u'build_commits_map',
    sa.Column(u'build_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column(u'commit_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['build_id'], [u'build.id'], name=u'build_commits_map_build_id_fkey'),
    sa.ForeignKeyConstraint(['commit_id'], [u'commit.id'], name=u'build_commits_map_commit_id_fkey'),
    sa.PrimaryKeyConstraint()
    )

    build = sa.sql.table('build', sa.sql.column('id', sa.Integer()), sa.sql.column('commit_id', sa.Integer()))
    build_commits_map = sa.sql.table('build_commits_map', sa.sql.column('build_id', sa.Integer()), sa.sql.column('commit_id', sa.Integer()))

    builds = op.get_bind().execute(build.select())
    ins = [{'build_id': b[build.c.id], 'commit_id': b[build.c.commit_id]} for b in builds]
    if ins:
        op.bulk_insert(build_commits_map, ins)

    op.drop_column('build', 'commit_id')
    ### end Alembic commands ###
