"""Adds secondary pool table

Revision ID: 15c03dfe15a5
Revises: 544e077e70f9
Create Date: 2013-12-13 12:56:01.639033

"""

# revision identifiers, used by Alembic.
revision = '15c03dfe15a5'
down_revision = '544e077e70f9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('secondary_pool',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('min_ready', sa.Integer(), nullable=False),
    sa.Column('max_running', sa.Integer(), nullable=False),
    sa.Column('instance_type', sa.String(), nullable=False),
    sa.Column('ami_id', sa.String(), nullable=False),
    sa.Column('vm_username', sa.String(), nullable=False),
    sa.Column('root_drive_size', sa.Integer(), nullable=False),
    sa.Column('user_data', sa.String(), nullable=True),
    sa.Column('deleted', sa.Integer(), nullable=False),
    sa.CheckConstraint('deleted = 0 OR id = deleted'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name','deleted')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('secondary_pool')
    ### end Alembic commands ###
