"""Adding new special users to the database

Revision ID: 18d08ab3a7b9
Revises: 10c6543b5424
Create Date: 2013-04-19 12:42:29.446425

"""

# revision identifiers, used by Alembic.
revision = '18d08ab3a7b9'
down_revision = '10c6543b5424'

from alembic import op
import sqlalchemy as sa

from database import schema


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('build', u'commit_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    ### end Alembic commands ###

    schema.insert_admin_user()
    schema.insert_admin_api_user()
    schema.insert_admin_verifier()


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('build', u'commit_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    ### end Alembic commands ###
    user = sa.sql.table('user', sa.sql.column('id', sa.Integer()))
    op.get_bind().execute(user.delete().where(user.c.id == 1))
    op.get_bind().execute(user.delete().where(user.c.id == 2))
    op.get_bind().execute(user.delete().where(user.c.id == 3))
