"""Initial database revision

Revision ID: 1c3fe885d43d
Revises: None
Create Date: 2013-03-25 12:25:02.719491

"""

# revision identifiers, used by Alembic.
revision = '1c3fe885d43d'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_name', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('property_name')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meta')
    ### end Alembic commands ###
