"""Adding system settings and license tables

Revision ID: 1c4e5d7f2142
Revises: 40c1ecee6a2
Create Date: 2013-03-29 15:17:17.426567

"""

# revision identifiers, used by Alembic.
revision = '1c4e5d7f2142'
down_revision = '40c1ecee6a2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
