"""Adding tables for patch and xunit

Revision ID: 2785518efe6e
Revises: 1850579c138
Create Date: 2013-08-19 23:25:55.104688

"""

# revision identifiers, used by Alembic.
revision = '2785518efe6e'
down_revision = '1850579c138'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('change_id', sa.Integer(), nullable=False),
    sa.Column('contents', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['change_id'], ['change.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('xunit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('build_console_id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('contents', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['build_console_id'], ['build_console.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('build_console_id','path')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('xunit')
    op.drop_table('patch')
    ### end Alembic commands ###
