"""Add github commit owner data

Revision ID: 2b278a305caf
Revises: 31a259340697
Create Date: 2013-09-12 13:06:24.408509

"""

# revision identifiers, used by Alembic.
revision = '2b278a305caf'
down_revision = '31a259340697'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('commit', sa.Column('committer_email', sa.String(), nullable=True))
    op.add_column('commit', sa.Column('committer_name', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('commit', 'committer_name')
    op.drop_column('commit', 'committer_email')
    ### end Alembic commands ###
