"""Adds pool_id column to virtual_machine

Revision ID: 2feeb44a0f10
Revises: 15c03dfe15a5
Create Date: 2013-12-28 15:06:44.788761

"""

# revision identifiers, used by Alembic.
revision = '2feeb44a0f10'
down_revision = '15c03dfe15a5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('virtual_machine', sa.Column('pool_id', sa.Integer(), nullable=True))

    virtual_machine = sa.sql.table('virtual_machine', sa.sql.column('id', sa.Integer()), sa.sql.column('pool_id', sa.Integer()))
    op.get_bind().execute(virtual_machine.update().values(pool_id=0))

    op.alter_column('virtual_machine', 'pool_id', nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('virtual_machine', 'pool_id')
    ### end Alembic commands ###
