"""Add github repo metadata table

Revision ID: 31a259340697
Revises: e689879ce67
Create Date: 2013-08-30 19:03:08.962353

"""

# revision identifiers, used by Alembic.
revision = '31a259340697'
down_revision = 'e689879ce67'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('github_repo_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repo_id', sa.Integer(), nullable=False),
    sa.Column('github_repo_name', sa.String(), nullable=False),
    sa.Column('hook_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['repo_id'], ['repo.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repo_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('github_repo_metadata')
    ### end Alembic commands ###
