"""Add repo type column

Revision ID: 36bf36d2dce8
Revises: 1fc8dfcd1f5d
Create Date: 2013-08-05 15:31:44.749289

"""

# revision identifiers, used by Alembic.
revision = '36bf36d2dce8'
down_revision = '1fc8dfcd1f5d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repo', sa.Column('type', sa.String(), nullable=True))

    repo = sa.sql.table('repo', sa.sql.column('id', sa.Integer()), sa.sql.column('type', sa.String()))
    op.get_bind().execute(repo.update().values(type='git'))

    op.alter_column('repo', 'type', nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repo', 'type')
    ### end Alembic commands ###
