"""Add GitHub OAuth token

Revision ID: 3f18d444f38f
Revises: 36bf36d2dce8
Create Date: 2013-07-18 16:13:51.746505

"""

# revision identifiers, used by Alembic.
revision = '3f18d444f38f'
down_revision = '36bf36d2dce8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column(u'github_oauth', sa.VARCHAR()))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', u'github_oauth')
    ### end Alembic commands ###
