"""Add export_url to change table

Revision ID: 3fb6a3072672
Revises: 18d08ab3a7b9
Create Date: 2013-04-22 16:17:08.657869

"""

# revision identifiers, used by Alembic.
revision = '3fb6a3072672'
down_revision = '18d08ab3a7b9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('change', sa.Column(u'export_url', sa.VARCHAR(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('change', u'export_url')
    ### end Alembic commands ###
