"""1st revision with tables

Revision ID: 40c1ecee6a2
Revises: 482ef263adbb
Create Date: 2013-03-29 15:16:24.987289

"""

# revision identifiers, used by Alembic.
revision = '40c1ecee6a2'
down_revision = '482ef263adbb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
