"""Add pending column to commit table

Revision ID: 49757f127970
Revises: 1173ebf00891
Create Date: 2013-04-25 17:58:39.311609

"""

# revision identifiers, used by Alembic.
revision = '49757f127970'
down_revision = '1173ebf00891'

from alembic import op
import sqlalchemy as sa


def upgrade():
	### commands auto generated by Alembic - please adjust! ###
	op.add_column('commit', sa.Column('pending', sa.Boolean(), nullable=True))

	commit = sa.sql.table('commit', sa.sql.column('id', sa.Integer()), sa.sql.column('pending', sa.Boolean()))
	op.get_bind().execute(commit.update().values(pending=True))

	op.alter_column('commit', 'pending', nullable=False)

	### end Alembic commands ###


def downgrade():
	### commands auto generated by Alembic - please adjust! ###
	op.drop_column('commit', 'pending')
	### end Alembic commands ###
