"""Add change export uri table

Revision ID: 51208e23491
Revises: 18d08ab3a7b9
Create Date: 2013-04-22 19:42:35.971663

"""

# revision identifiers, used by Alembic.
revision = '51208e23491'
down_revision = '18d08ab3a7b9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('change_export_uri',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('change_id', sa.Integer(), nullable=False),
    sa.Column('uri', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['change_id'], ['change.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('change_id','uri')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('change_export_uri')
    ### end Alembic commands ###
