"""Add virtual_machine

Revision ID: e689879ce67
Revises: 10b0fad87127
Create Date: 2013-08-30 14:44:54.621213

"""

# revision identifiers, used by Alembic.
revision = 'e689879ce67'
down_revision = '10b0fad87127'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('virtual_machine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('instance_id', sa.String(), nullable=False),
    sa.Column('pool_slot', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('virtual_machine')
    ### end Alembic commands ###
