---
setup:
  - packages:
    - system:
      - build-essential
      - python-nose
      - redis-server
      - vagrant
      - libevent-dev
    - pip:
      - pika
      - kombu
      - sqlalchemy
      - pyyaml
      - msgpack-python
      - nose
      - beautifulsoup4
      - dulwich
      - redis
      - greenlet
      - gevent
      - gitpython
build:
  python
