// Generated by CoffeeScript 1.3.3
(function() {
  var HelloHandler, bridge;

  bridge = new (require('bridge-js'))({
    apiKey: 'dfikjjgmhmdahhlg',
    host: '127.0.0.1',
    port: 8090
  });

  bridge.connect();

  HelloHandler = (function() {

    function HelloHandler() {}

    HelloHandler.prototype.hello = function(callback) {
      return callback('sup node nerd?');
    };

    return HelloHandler;

  })();

  bridge.publishService('helloWorld', new HelloHandler);

  console.log('node bridge server is running!!');

}).call(this);
