---
setup:
  - packages:
    - system:
      - zlib1g
      - vim
      - gcc
      - g++
      - curl
      - libssl-dev
      - apache2-utils
      - libevent-dev
      - libpq-dev
    - pip:
      - amqp
      - pika
      - kombu
      - librabbitmq
      - sqlalchemy
      - pyyaml
      - msgpack-python
      - nose
      - beautifulsoup4
      - dulwich
      - ipython
      - redis
      - greenlet
      - gevent
      - gitpython
      - virtualenvwrapper
      - psycopg2
      - argparse
      - nose-testconfig
      - boto
    - gem:
      - vagrant
    - npm:
      - iced-coffee-script
  - scripts:
    - script: ./install_virtualbox.sh
      directory: ci/scripts
  - databases:
      postgres:
      - name: agles
        connection-info:
          host: localhost
          port: 5432
          username: postgres
  - scripts:
    - script: npm install
      directory: ci/web/back
build:
  python:
    version: 2.7
    buildscript:
    path: platform
    testscript: nosetests
  ruby:
    version: 1.9.3
  node:
    version: v0.8.9
