---
setup:
  - packages:
    - system:
      - python-software-properties
      - zlib1g
      - vim
      - gcc
      - g++
      - curl
      - libssl-dev
      - apache2-utils
      - libevent-dev
      - libpq-dev
      - lessc
      - haproxy
      - maven
    - pip:
      - amqp
      - pika: 0.9.5
      - kombu: 2.5.3
      - librabbitmq
      - sqlalchemy
      - pyyaml
      - msgpack-python
      - nose
      - beautifulsoup4
      - dulwich
      - ipython
      - redis
      - greenlet
      - eventlet
      - gitpython
      - psycopg2
      - argparse
      - nose-testconfig
      - boto
      - rackspace-novaclient
      - requests
    - gem:
      - vagrant
    - npm:
      - iced-coffee-script
      - less
      - directory: ci/web/back
  - scripts:
    - script: ./install_virtualbox.sh
      directory: ci/scripts
    - script: vagrant gem install sahara
      user: true
    - script: |
        if [ ! -d "/usr/lib/jvm/java-6-sun" ]
          then mkdir /tmp/src
          cd /tmp/src
          git clone https://github.com/flexiondotorg/oab-java6.git
          cd /tmp/src/oab-java6
          ./oab-java.sh
          add-apt-repository ppa:flexiondotorg/java
          apt-get update
        fi
  - packages:
    - system:
      - sun-java6-jdk
  - databases:
      postgres:
      - name: koality
        username: lt3
languages:
  # python: 2.7 # This would put pip packages in a virtualenv
  ruby: 1.9.3
  nodejs: v0.8.9
