---
setup:
  - packages:
    - system:
      - zlib1g
      - vim
      - gcc
      - g++
      - curl
      - libssl-dev
      - apache2-utils
      - libevent-dev
      - libpq-dev
      - lessc
      - haproxy
    - pip:
      - amqp
      - pika: 0.9.5
      - kombu
      - librabbitmq
      - sqlalchemy
      - pyyaml
      - msgpack-python
      - nose
      - beautifulsoup4
      - dulwich
      - ipython
      - redis
      - greenlet
      - eventlet
      - gitpython
      - virtualenvwrapper
      - psycopg2
      - argparse
      - nose-testconfig
      - boto
    - gem:
      - vagrant
    - npm:
      - iced-coffee-script
      - less
      - directory: ci/web/back
  - scripts:
    - script: ./install_virtualbox.sh
      directory: ci/scripts
    - script: vagrant gem install sahara
      user: true
  - databases:
      postgres:
      - name: koality
        username: lt3
languages:
  python: 2.7
  ruby: 1.9.3
  nodejs: v0.8.9
