---
setup:
  - packages:
    - system:
      - zlib1g
      - vim
      - gcc
      - g++
      - curl
      - libssl-dev
      - apache2-utils
      - libevent-dev
      - libpq-dev
      - lessc
      - haproxy
      - mvn
    - scripts:
      - script:|
          sudo add-apt-repository ppa:flexiondotorg/java
          sudo apt-get update
          sudo apt-get install sun-java6-jdk sun-java6-plugin
    - pip:
      - amqp
      - pika: 0.9.5
      - kombu: 2.5.3
      - librabbitmq
      - sqlalchemy
      - pyyaml
      - msgpack-python
      - nose
      - beautifulsoup4
      - dulwich
      - ipython
      - redis
      - greenlet
      - eventlet
      - gitpython
      - psycopg2
      - argparse
      - nose-testconfig
      - boto
      - rackspace-novaclient
    - gem:
      - vagrant
    - npm:
      - iced-coffee-script
      - less
      - directory: ci/web/back
  - scripts:
    - script: ./install_virtualbox.sh
      directory: ci/scripts
    - script: vagrant gem install sahara
      user: true
  - databases:
      postgres:
      - name: koality
        username: lt3
languages:
  # python: 2.7 # This would put pip packages in a virtualenv
  ruby: 1.9.3
  nodejs: v0.8.9
